package watch.entity;
// Generated Nov 4, 2020 2:35:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private String catId;
     private String catName;
     private Boolean catStatus;
     private String descriptons;
     private Set products = new HashSet(0);

    public Categories() {
    }

	
    public Categories(String catId) {
        this.catId = catId;
    }
    public Categories(String catId, String catName, Boolean catStatus, String descriptons, Set products) {
       this.catId = catId;
       this.catName = catName;
       this.catStatus = catStatus;
       this.descriptons = descriptons;
       this.products = products;
    }
   
    public String getCatId() {
        return this.catId;
    }
    
    public void setCatId(String catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Boolean getCatStatus() {
        return this.catStatus;
    }
    
    public void setCatStatus(Boolean catStatus) {
        this.catStatus = catStatus;
    }
    public String getDescriptons() {
        return this.descriptons;
    }
    
    public void setDescriptons(String descriptons) {
        this.descriptons = descriptons;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


