package watch.entity;
// Generated Nov 4, 2020 2:35:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String productId;
     private Categories categories;
     private Producers producers;
     private String productName;
     private Double price;
     private String title;
     private String descriptions;
     private String created;
     private Integer discount;
     private Integer quantity;
     private String imageLink;
     private Boolean productStatus;
     private Set imageses = new HashSet(0);
     private Set orderDetails = new HashSet(0);

    public Product() {
    }

	
    public Product(String productId) {
        this.productId = productId;
    }
    public Product(String productId, Categories categories, Producers producers, String productName, Double price, String title, String descriptions, String created, Integer discount, Integer quantity, String imageLink, Boolean productStatus, Set imageses, Set orderDetails) {
       this.productId = productId;
       this.categories = categories;
       this.producers = producers;
       this.productName = productName;
       this.price = price;
       this.title = title;
       this.descriptions = descriptions;
       this.created = created;
       this.discount = discount;
       this.quantity = quantity;
       this.imageLink = imageLink;
       this.productStatus = productStatus;
       this.imageses = imageses;
       this.orderDetails = orderDetails;
    }
   
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Producers getProducers() {
        return this.producers;
    }
    
    public void setProducers(Producers producers) {
        this.producers = producers;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public String getCreated() {
        return this.created;
    }
    
    public void setCreated(String created) {
        this.created = created;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }
    public Boolean getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(Boolean productStatus) {
        this.productStatus = productStatus;
    }
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


