package watch.entity;
// Generated Nov 4, 2020 2:35:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Producers generated by hbm2java
 */
public class Producers  implements java.io.Serializable {


     private String producersId;
     private String producersName;
     private Boolean productStatus;
     private Set products = new HashSet(0);

    public Producers() {
    }

	
    public Producers(String producersId) {
        this.producersId = producersId;
    }
    public Producers(String producersId, String producersName, Boolean productStatus, Set products) {
       this.producersId = producersId;
       this.producersName = producersName;
       this.productStatus = productStatus;
       this.products = products;
    }
   
    public String getProducersId() {
        return this.producersId;
    }
    
    public void setProducersId(String producersId) {
        this.producersId = producersId;
    }
    public String getProducersName() {
        return this.producersName;
    }
    
    public void setProducersName(String producersName) {
        this.producersName = producersName;
    }
    public Boolean getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(Boolean productStatus) {
        this.productStatus = productStatus;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


